### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.protobuf.LazyStringList.getUnmodifiableView()Lcom/google/protobuf/LazyStringList

### ISSUE THREAD

**Issue by jcf** [riemann/riemann-clojure-client#27]
I'm getting the following error when sending events to Riemann. I'm not certain of the cause, but it looks like an issue with converting event hash maps into Protobuf events.

```
java.lang.NoSuchMethodError: com.google.protobuf.LazyStringList.getUnmodifiableView()Lcom/google/protobuf/LazyStringList;
	at com.aphyr.riemann.Proto$Event$Builder.buildPartial(Proto.java:2320)
	at com.aphyr.riemann.Proto$Event$Builder.build(Proto.java:2288)
	at riemann.codec$encode_pb_event.invokeStatic(codec.clj:88)
	at riemann.codec$encode_pb_event.invoke(codec.clj:65)
	at riemann.codec$encode_client_pb_event.invokeStatic(codec.clj:94)
	at riemann.codec$encode_client_pb_event.invoke(codec.clj:90)
	at clojure.core$map$fn__4785.invoke(core.clj:2644)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.lang.SeqIterator.hasNext(SeqIterator.java:38)
	at com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:336)
	at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:323)
	at com.aphyr.riemann.Proto$Msg$Builder.addAllEvents(Proto.java:5118)
	at com.aphyr.riemann.client.RiemannClient.sendEvents(RiemannClient.java:125)
	at riemann.client$send_events.invokeStatic(client.clj:63)
	at riemann.client$send_events.invoke(client.clj:58)
	at onyx.metrics.riemann$riemann_sender$fn__31981$fn__31990.invoke(riemann.clj:57)
	at onyx.metrics.riemann$riemann_sender$fn__31981.invoke(riemann.clj:55)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using version `0.4.2` of the Riemann Clojure client, and rolling back to `0.4.1` doesn't appear to help.

Has anyone else experienced this issue?

**Comment by jcf** [comment]
I think there's a dependency issue somewhere that's causing this, but not sure where.

Related issue on Spark CoreNLP: https://github.com/databricks/spark-corenlp/issues/4

**Comment by jcf** [comment]
Looks like adding an explicit dependency on `protobuf-java` fixes the issue.

``` clj
[com.google.protobuf/protobuf-java "3.1.0"]
```

**Comment by mcorbin** [comment]
I never had this problem. I just created a new clojure project with `[riemann-clojure-client "0.4.2"]` in dependency and it works.
Furthermore, the protobuf version actually used in the riemann-java-client is "2.6.1".

**Comment by jcf** [comment]
@mcorbin You need to pull in other libraries to get a conflict.

**Comment by belkacemlahouel** [comment]
Hey guys! Just had the same issue, I can't manage to solve it. It's been a long time, but any other clues?
