### ISSUE TITLE
`metric` attributes overrides metric field on event

### ISSUE THREAD

**Issue by also** [riemann/riemann-clojure-client#4]
Running the "Quickstart" example with current (0.2.0) Ruby client generates an event with a "metrics" **attribute**. `riemann.codec/decode-pb-event` return an event that has this string instead of a number as the metric. This leads to failures like 

```
WARN [2013-04-02 03:14:54,956] pool-1-thread-4 - riemann.config - riemann.streams$over$stream__1354@40d6dec threw
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
	at clojure.lang.Numbers.lt(Numbers.java:219)
	at riemann.streams$over$stream__1354.invoke(streams.clj:1243)
	at riemann.config$eval1535$stream__1407__auto____1539$fn__1547.invoke(riemann.config:22)
	at riemann.config$eval1535$stream__1407__auto____1539.invoke(riemann.config:22)
	at riemann.transport$handle.invoke(transport.clj:103)
	at riemann.transport.udp$udp_handler$fn__9720.invoke(udp.clj:34)
…
```

**Comment by pyr** [comment]
apparently this is a riemann-ruby-client error
